### ISSUE TITLE
Использование кастомного токена

### ISSUE THREAD

**Issue by progfiles** [LiveTex/sdk-android#13]
Когда используем кастомный токен в методе **networkManager.connect(token, AuthTokenType.CUSTOM)**, то возвращается сгенерированый токен(отличающийся от исходного).
Вопрос: для чего использовать кастомный токен, если история не подтягивается и каждый раз генерируется новый токен.
Может надо по другому использовать этот функционал?

**Comment by maxxx** [comment]
разобрались, это проблема серверной стороны. Саппорт должен ответить когда проблема будет решена.
