### ISSUE TITLE
Странное поведение метода ru.livetex.sdk.entity.DialogState#isInputEnabled

### ISSUE THREAD

**Issue by xBlackCat** [LiveTex/sdk-android#24]
Значение поля inputEnabled = null превращается в isInputEnabled() == true. Такое поведение отличается от поведения SDK для iOS, где inputEnabled = null превращается в false

Дополнительный реквест: дайте доступ к полю inputEnabled для возможности работы с тремя состояниями: null, true и false. Это даст больше гибкости в использовании Android SDK

**Comment by maxxx** [comment]
Привет. Подразумевалось что если от сервера нет ограничений (inputEnabled = null) то никаких ограничений на поля ввода не накладывается. Странно что на айос по-другому, обсудим. 
Паблик сделаю, и еще метод переименуется в canShowInput() (потому что оперируем видимостью а не включенностью)
