### ISSUE TITLE
После добавления зависимости в проект - android studio не видит класс LiveTex 

### ISSUE THREAD

**Issue by veldyasov** [LiveTex/sdk-android#8]
После добавления зависимости в проект 
implementation 'com.github.LiveTex:sdk-android:1.2'
android studio не видит класс LiveTex и другие классы, доступны только 2 класса:
EntityMapper.LivetexTypeModelDeserializer
LiveTexError

**Comment by maxxx** [comment]
Спасибо, должно быть исправлено в 1.2.1

**Comment by veldyasov** [comment]
Новая версия не резолвится
Failed to resolve: com.github.LiveTex:sdk-android:1.2.1

**Comment by maxxx** [comment]
Странно, через какое-то время исчезли pom файлы. Пересобрал, пока что все на месте (https://jitpack.io/com/github/LiveTex/sdk-android/1.2.1/)
